// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, password, first_name, last_name, phone_prefix, phone_number, role_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, email, first_name, last_name, phone_prefix, phone_number, created_at, updated_at, deleted_at, password, role_id
`

type CreateUserParams struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	PhonePrefix string `json:"phone_prefix"`
	PhoneNumber string `json:"phone_number"`
	RoleID      string `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.PhonePrefix,
		arg.PhoneNumber,
		arg.RoleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhonePrefix,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Password,
		&i.RoleID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execresult
UPDATE users
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUser, id)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, phone_prefix, phone_number, created_at, updated_at, deleted_at, password, role_id FROM users
WHERE email = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhonePrefix,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Password,
		&i.RoleID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT users.id, users.email, users.first_name, users.last_name, users.phone_prefix, users.phone_number, users.created_at, users.updated_at, users.deleted_at, users.password, users.role_id, 
    roles.id, roles.name, roles.created_at, roles.updated_at, roles.deleted_at FROM users
LEFT JOIN roles ON users.role_id = roles.id
WHERE users.id = $1 AND users.deleted_at IS NULL LIMIT 1
`

type GetUserByIDRow struct {
	User User `json:"user"`
	Role Role `json:"role"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.PhonePrefix,
		&i.User.PhoneNumber,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.User.Password,
		&i.User.RoleID,
		&i.Role.ID,
		&i.Role.Name,
		&i.Role.CreatedAt,
		&i.Role.UpdatedAt,
		&i.Role.DeletedAt,
	)
	return i, err
}

const getUserForAuth = `-- name: GetUserForAuth :one
SELECT id,email, password FROM users
WHERE email = $1 AND deleted_at IS NULL LIMIT 1
`

type GetUserForAuthRow struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) GetUserForAuth(ctx context.Context, email string) (GetUserForAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserForAuth, email)
	var i GetUserForAuthRow
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT 
    users.id, users.email, users.first_name, users.last_name, users.phone_prefix, users.phone_number, users.created_at, users.updated_at, users.deleted_at, users.password, users.role_id, 
    roles.id, roles.name, roles.created_at, roles.updated_at, roles.deleted_at
FROM users
LEFT JOIN roles ON users.role_id = roles.id
WHERE 
    (users.deleted_at IS NULL)
    AND (users.role_id = $3::uuid OR $3 IS NULL)
    AND (
        $4::text IS NULL OR 
        users.first_name ILIKE '%' || $4 || '%' OR 
        users.last_name ILIKE '%' || $4 || '%' OR 
        users.email ILIKE '%' || $4 || '%'
    )
ORDER BY 
    CASE WHEN $5 = 'first_name' AND $6 = 'asc' THEN users.first_name END ASC,
    CASE WHEN $5 = 'first_name' AND $6 = 'desc' THEN users.first_name END DESC,
    CASE WHEN $5 = 'created_at' AND $6 = 'asc' THEN users.created_at END ASC,
    users.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	RoleID  pgtype.UUID `json:"role_id"`
	Search  pgtype.Text `json:"search"`
	SortBy  interface{} `json:"sort_by"`
	SortDir interface{} `json:"sort_dir"`
}

type ListUsersRow struct {
	User User `json:"user"`
	Role Role `json:"role"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Limit,
		arg.Offset,
		arg.RoleID,
		arg.Search,
		arg.SortBy,
		arg.SortDir,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Email,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.PhonePrefix,
			&i.User.PhoneNumber,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
			&i.User.Password,
			&i.User.RoleID,
			&i.Role.ID,
			&i.Role.Name,
			&i.Role.CreatedAt,
			&i.Role.UpdatedAt,
			&i.Role.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, 
    first_name = $3, 
    last_name = $4, 
    phone_prefix = $5, 
    phone_number = $6, 
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, first_name, last_name, phone_prefix, phone_number, created_at, updated_at, deleted_at, password, role_id
`

type UpdateUserParams struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	PhonePrefix string `json:"phone_prefix"`
	PhoneNumber string `json:"phone_number"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PhonePrefix,
		arg.PhoneNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhonePrefix,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Password,
		&i.RoleID,
	)
	return i, err
}
